name: pabrik_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.2.0+3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  google_fonts: ^6.3.0
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.1.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  animate_do: ^4.2.0
  flutter_dotenv: ^6.0.0
  get_it: ^8.2.0
  photo_view: ^0.15.0
  http_parser: ^4.1.2
  marquee: ^2.2.3
  image: ^4.1.0
  geolocator: ^12.0.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  safe_device: ^1.1.8
  flutter_launcher_icons: ^0.13.1
  image_cropper: ^8.0.2
  flutter_typeahead: ^5.2.0
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/background_login.png
    - assets/watermark.png
    - assets/profile_bg.png
    - assets/logo_splash.png
    - assets/icon_app.png
    - .env

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon_app.png"
  adaptive_icon_foreground: "assets/icon_app.png"
  adaptive_icon_background: "#FFFFFF"

flutter_native_splash:
  color: "#1A237E"
  image: assets/logo_splash.png
  android_gravity: center
  ios: true